name: Cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  check_for_changes: 
    runs-on: ubuntu-latest
    name: Merge develop into master
    steps: 
      - name: Tell time
        run: echo "$(date +'%d/%m/%Y %H:%M:%S:%3N')"
